// GENERATED BY PROMPT — Placeholder tokens used — DO NOT PASTE REAL SECRETS

(function() {
    'use strict';
    
    // State management
    const state = {
        currentRoute: '/',
        theme: localStorage.getItem('theme') || 'light',
        interactionsEndpoint: localStorage.getItem('interactionsEndpoint') || 'https://your-bot-api.com/interactions',
        models: {
            deepseek: [
                { name: "DeepSeek Chat", id: "deepseek-chat" },
                { name: "DeepSeek DeepThink", id: "deepseek-reasoner" }
            ],
            chatgpt: [
                { name: "GPT-5", id: "gpt-5.1" },
                { name: "GPT-4", id: "gpt-4o" }
            ],
            claude: [
                { name: "Claude Opus", id: "claude-opus-4-5-latest" },
                { name: "Claude Haiku", id: "claude-haiku-4.5" },
                { name: "Claude Sonnet", id: "claude-sonnet-4.5" }
            ],
            grok: [
                { name: "Grok 3", id: "grok-3" },
                { name: "Grok Fast", id: "grok-3-fast" },
                { name: "Grok Mini", id: "grok-3-mini" },
                { name: "Grok Mini Fast", id: "grok-3-mini-fast" }
            ],
            gemini: [
                { name: "Gemini Flash", id: "gemini-2.5-flash" },
                { name: "Gemini Flash Lite", id: "gemini-2.5-flash-lite" },
                { name: "Gemini Pro", id: "gemini-2.5-pro" }
            ],
            qwen: [
                { name: "Qwen thinking", id: "openrouter:qwen/qwen3-vl-8b-thinking" },
                { name: "Qwen instruct", id: "openrouter:qwen/qwen3-vl-8b-instruct" }
            ]
        }
    };
    
    // DOM Elements
    const routerView = document.getElementById('router-view');
    const navToggle = document.querySelector('.nav-toggle');
    const navMenu = document.getElementById('nav-menu');
    const connectBtn = document.getElementById('connect-btn');
    const connectModal = document.getElementById('connect-modal');
    const modalClose = document.querySelector('.modal-close');
    const themeToggle = document.getElementById('theme-toggle');
    
    // Initialize the application
    function init() {
        setupEventListeners();
        setupRouting();
        applyTheme(state.theme);
        renderRoute(state.currentRoute);
    }
    
    // Event Listeners
    function setupEventListeners() {
        // Navigation toggle for mobile
        navToggle.addEventListener('click', toggleMobileMenu);
        
        // Modal controls
        connectBtn.addEventListener('click', openConnectModal);
        modalClose.addEventListener('click', closeConnectModal);
        connectModal.addEventListener('click', function(e) {
            if (e.target === connectModal) closeConnectModal();
        });
        
        // Theme toggle
        themeToggle.addEventListener('click', toggleTheme);
        
        // Handle escape key for modals
        document.addEventListener('keydown', function(e) {
            if (e.key === 'Escape') {
                closeConnectModal();
            }
        });
        
        // Handle hash changes for routing
        window.addEventListener('hashchange', handleHashChange);
        
        // Handle initial hash
        if (window.location.hash) {
            handleHashChange();
        }
    }
    
    // Mobile menu functionality
    function toggleMobileMenu() {
        const isExpanded = navToggle.getAttribute('aria-expanded') === 'true';
        navToggle.setAttribute('aria-expanded', !isExpanded);
        navMenu.setAttribute('aria-expanded', !isExpanded);
    }
    
    // Modal functionality
    function openConnectModal() {
        connectModal.setAttribute('aria-hidden', 'false');
        document.body.style.overflow = 'hidden';
    }
    
    function closeConnectModal() {
        connectModal.setAttribute('aria-hidden', 'true');
        document.body.style.overflow = '';
    }
    
    // Theme functionality
    function toggleTheme() {
        const newTheme = state.theme === 'light' ? 'dark' : 'light';
        applyTheme(newTheme);
        state.theme = newTheme;
        localStorage.setItem('theme', newTheme);
    }
    
    function applyTheme(theme) {
        document.documentElement.setAttribute('data-theme', theme);
        const themeIcon = themeToggle.querySelector('.theme-icon');
        themeIcon.textContent = theme === 'light' ? '🌙' : '☀️';
    }
    
    // Routing functionality
    function setupRouting() {
        const hash = window.location.hash.slice(1) || '/';
        state.currentRoute = hash;
        updateActiveNavLink(hash);
    }
    
    function handleHashChange() {
        const hash = window.location.hash.slice(1) || '/';
        state.currentRoute = hash;
        updateActiveNavLink(hash);
        renderRoute(hash);
    }
    
    function updateActiveNavLink(route) {
        document.querySelectorAll('.nav-link').forEach(link => {
            link.classList.remove('active');
            if (link.getAttribute('data-route') === route) {
                link.classList.add('active');
            }
        });
    }
    
    // Route rendering
    function renderRoute(route) {
        let content = '';
        
        switch(route) {
            case '/':
                content = renderHome();
                break;
            case '/interactions':
                content = renderInteractions();
                break;
            case '/features':
                content = renderFeatures();
                break;
            case '/models':
                content = renderModels();
                break;
            case '/tos':
                content = renderTOS();
                break;
            case '/privacy':
                content = renderPrivacy();
                break;
            default:
                content = renderHome();
        }
        
        routerView.innerHTML = content;
        
        // Attach event listeners for dynamic content
        if (route === '/interactions') {
            attachInteractionsListeners();
        } else if (route === '/') {
            attachHomeListeners();
        }
        
        // Initialize copy buttons
        initCopyButtons();
        
        // Scroll to top on route change
        window.scrollTo(0, 0);
    }
    
    // Home page rendering
    function renderHome() {
        return `
            <section class="hero">
                <h1 class="hero-title">AI Discord Bot with PuterClient</h1>
                <p class="hero-subtitle">A powerful Discord bot featuring multiple AI models, comprehensive logging, and intelligent command handling. Built with Python and PuterClient for seamless AI integration.</p>
                
                <div class="features">
                    <div class="feature-card">
                        <div class="feature-icon">🤖</div>
                        <h3 class="feature-title">Multiple AI Models</h3>
                        <p class="feature-description">Access DeepSeek, GPT-4, Claude, Grok, Gemini, and Qwen models through a single bot interface with PuterClient integration.</p>
                    </div>
                    <div class="feature-card">
                        <div class="feature-icon">📝</div>
                        <h3 class="feature-title">Comprehensive Logging</h3>
                        <p class="feature-description">Detailed message logging with timestamps, server/channel info, and user data for moderation and analytics.</p>
                    </div>
                    <div class="feature-card">
                        <div class="feature-icon">💬</div>
                        <h3 class="feature-title">DM & Command Support</h3>
                        <p class="feature-description">Respond to DMs automatically and support hybrid commands with both text and slash command interfaces.</p>
                    </div>
                </div>
                
                <div class="info-box">
                    <h3>Quick Start</h3>
                    <p>To set up your bot, you need to configure your Discord token and use the PuterClient for AI model access. Check the "Bot Features" page for detailed setup instructions.</p>
                </div>
            </section>
        `;
    }
    
    // Interactions page rendering
    function renderInteractions() {
        return `
            <section class="page-content">
                <h1>Discord Interactions & Webhooks</h1>
                <p>Configure your bot's interaction endpoints and webhooks for receiving Discord events and commands.</p>
                
                <div class="warning-box">
                    <strong>⚠️ Security Warning:</strong> Never expose your bot token or Puter.com credentials. Store them securely in environment variables.
                </div>
                
                <h2>Bot Configuration Example</h2>
                <p>Your bot uses the following configuration structure:</p>
                
                <div class="code-block">
                    <button class="copy-btn" data-target="config-example">Copy</button>
                    <pre id="config-example"># .env file (DO NOT COMMIT THIS)
DISCORD_TOKEN=your_discord_bot_token_here

# Bot Configuration
import os
from dotenv import load_dotenv

load_dotenv()
token = os.getenv('DISCORD_TOKEN')

intents = discord.Intents.default()
intents.message_content = True
intents.members = True

bot = commands.Bot(command_prefix='§', intents=intents)</pre>
                </div>
                
                <h2>Interaction Endpoint Setup</h2>
                <p>For receiving interactions via HTTP POST instead of Gateway:</p>
                
                <form id="interactions-form">
                    <div class="form-group">
                        <label for="endpoint-url" class="form-label">Interactions Endpoint URL</label>
                        <input type="url" id="endpoint-url" class="form-input" 
                               value="${state.interactionsEndpoint}" 
                               placeholder="https://your-bot-api.com/interactions">
                    </div>
                    
                    <button type="button" class="btn btn-primary" id="save-interactions">Save Configuration</button>
                </form>
                
                <h2>Sample Bot Event Handler</h2>
                <div class="code-block">
                    <button class="copy-btn" data-target="event-handler">Copy</button>
                    <pre id="event-handler">@bot.event
async def on_ready():
    print(f'Logged on as {bot.user.name}')
    try:
        synced = await bot.tree.sync()
        print(f"Synced {len(synced)} command(s)")
    except Exception as e:
        print(f"Failed to sync commands: {e}")

@bot.event
async def on_message(message):
    # Log all messages
    log_message(message)
    
    if message.author.bot:
        return
    
    # Respond to DMs automatically
    if message.guild is None and message.author != bot.user:
        response = await deepseek(message.content, "deepseek-chat")
        await message.channel.send(response)
    
    await bot.process_commands(message)</pre>
                </div>
                
                <h2>Security Best Practices</h2>
                <ul>
                    <li>Store tokens in environment variables, never in source code</li>
                    <li>Use HTTPS for all endpoints</li>
                    <li>Implement proper error handling and logging</li>
                    <li>Validate all incoming interactions</li>
                    <li>Use rate limiting to prevent abuse</li>
                    <li>Regularly update dependencies</li>
                </ul>
            </section>
        `;
    }
    
    // Features page rendering
    function renderFeatures() {
        return `
            <section class="page-content">
                <h1>Bot Features & Commands</h1>
                <p>Your Discord bot includes comprehensive features for AI interaction, moderation, and user management.</p>
                
                <div class="command-list">
                    <div class="command-item">
                        <h3 class="command-name">/ask [prompt] [model]</h3>
                        <p class="command-description">Ask the AI to generate text using the specified model. Supports all major AI providers.</p>
                        <div class="command-usage">/ask "What is quantum computing?" model:gpt-4o</div>
                    </div>
                    
                    <div class="command-item">
                        <h3 class="command-name">/senddm [user] [message]</h3>
                        <p class="command-description">Send a direct message to a specified user. Supports user ID, mention, or username#discriminator.</p>
                        <div class="command-usage">/senddm @username Hello! This is a direct message.</div>
                    </div>
                    
                    <div class="command-item">
                        <h3 class="command-name">§reply [message]</h3>
                        <p class="command-description">Text command prefix response using the default AI model.</p>
                        <div class="command-usage">§reply What's the weather like today?</div>
                    </div>
                </div>
                
                <h2>Key Features</h2>
                
                <div class="features">
                    <div class="feature-card">
                        <div class="feature-icon">📊</div>
                        <h3 class="feature-title">Message Logging</h3>
                        <p class="feature-description">All messages are logged with timestamps, server info, channel details, and user information for complete audit trails.</p>
                    </div>
                    
                    <div class="feature-card">
                        <div class="feature-icon">🤖</div>
                        <h3 class="feature-title">AI Integration</h3>
                        <p class="feature-description">Seamless integration with PuterClient for accessing multiple AI models with intelligent response handling.</p>
                    </div>
                    
                    <div class="feature-card">
                        <div class="feature-icon">🛡️</div>
                        <h3 class="feature-title">Error Handling</h3>
                        <p class="feature-description">Comprehensive error handling with file-based responses for long messages and proper Discord permission checks.</p>
                    </div>
                </div>
                
                <h2>DeepSeek Function Integration</h2>
                <div class="code-block">
                    <button class="copy-btn" data-target="deepseek-function">Copy</button>
                    <pre id="deepseek-function">async def deepseek(set_prompt, set_model):
    async with PuterClient() as client:
        # Login to Puter.com
        await client.login("your_username", "your_password")
        
        # AI Chat with selected model
        result = await client.ai_chat(
            prompt=set_prompt,
            options={
                "model": set_model if set_model else "gpt-4o",
                "stream": False
            }
        )
        
        return result["response"]["result"]["message"]["content"]</pre>
                </div>
                
                <div class="warning-box">
                    <h3>Important Security Notes</h3>
                    <ul>
                        <li>Never hardcode Puter.com credentials in your bot code</li>
                        <li>Use environment variables or secure credential storage</li>
                        <li>Implement proper rate limiting for API calls</li>
                        <li>Monitor usage to prevent API abuse</li>
                    </ul>
                </div>
            </section>
        `;
    }
    
    // Models page rendering
    function renderModels() {
        return `
            <section class="page-content">
                <h1>Supported AI Models</h1>
                <p>Your bot supports multiple AI providers through PuterClient integration. Choose from various models for different use cases.</p>
                
                <h2>DeepSeek Models</h2>
                <div class="models-grid">
                    ${state.models.deepseek.map(model => `
                        <div class="model-card">
                            <div class="model-name">${model.name}</div>
                            <div class="model-id">${model.id}</div>
                        </div>
                    `).join('')}
                </div>
                
                <h2>ChatGPT Models</h2>
                <div class="models-grid">
                    ${state.models.chatgpt.map(model => `
                        <div class="model-card">
                            <div class="model-name">${model.name}</div>
                            <div class="model-id">${model.id}</div>
                        </div>
                    `).join('')}
                </div>
                
                <h2>Claude Models</h2>
                <div class="models-grid">
                    ${state.models.claude.map(model => `
                        <div class="model-card">
                            <div class="model-name">${model.name}</div>
                            <div class="model-id">${model.id}</div>
                        </div>
                    `).join('')}
                </div>
                
                <h2>Grok Models</h2>
                <div class="models-grid">
                    ${state.models.grok.map(model => `
                        <div class="model-card">
                            <div class="model-name">${model.name}</div>
                            <div class="model-id">${model.id}</div>
                        </div>
                    `).join('')}
                </div>
                
                <h2>Gemini Models</h2>
                <div class="models-grid">
                    ${state.models.gemini.map(model => `
                        <div class="model-card">
                            <div class="model-name">${model.name}</div>
                            <div class="model-id">${model.id}</div>
                        </div>
                    `).join('')}
                </div>
                
                <h2>Qwen Models</h2>
                <div class="models-grid">
                    ${state.models.qwen.map(model => `
                        <div class="model-card">
                            <div class="model-name">${model.name}</div>
                            <div class="model-id">${model.id}</div>
                        </div>
                    `).join('')}
                </div>
                
                <h2>Model Selection Example</h2>
                <div class="code-block">
                    <button class="copy-btn" data-target="model-usage">Copy</button>
                    <pre id="model-usage">@bot.hybrid_command(name="ask", description="Ask the AI to generate text or create an image")
@app_commands.choices(model=[
    app_commands.Choice(name="DeepSeek Chat", value="deepseek-chat"),
    app_commands.Choice(name="GPT-4", value="gpt-4o"),
    app_commands.Choice(name="Claude Opus", value="claude-opus-4-5-latest"),
    # ... more models
])
async def ask(ctx, user_prompt: str, model: app_commands.Choice[str] = None):
    model_value = model.value if model else None
    response = await deepseek(user_prompt, model_value)
    
    if len(response) > 2000:
        # Send as file if response is too long
        filename = f"response_{timestamp}.txt"
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(response)
        await ctx.send(file=discord.File(filename))
        os.remove(filename)
    else:
        embed = discord.Embed(title="AI Response", description=response)
        if model:
            embed.set_footer(text=f"Model: {model}")
        await ctx.send(embed=embed)</pre>
                </div>
                
                <div class="info-box">
                    <h3>Model Recommendations</h3>
                    <ul>
                        <li><strong>General Chat:</strong> DeepSeek Chat or GPT-4o</li>
                        <li><strong>Reasoning Tasks:</strong> DeepSeek DeepThink or Claude Opus</li>
                        <li><strong>Fast Responses:</strong> Claude Haiku or Grok Fast</li>
                        <li><strong>Creative Writing:</strong> Claude Sonnet or Gemini Pro</li>
                    </ul>
                </div>
            </section>
        `;
    }
    
    // Terms of Service page rendering
    function renderTOS() {
        const currentDate = new Date().toISOString().split('T')[0];
        
        return `
            <section class="page-content">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: var(--space-xl);">
                    <h1>Terms of Service</h1>
                    <button class="btn btn-secondary" onclick="window.print()">Print / Save as PDF</button>
                </div>
                
                <article>
                    <section>
                        <h2>1. Introduction</h2>
                        <p>These Terms of Service govern your use of the AI Discord Bot ("the Bot"). By using the Bot, you agree to these terms.</p>
                    </section>
                    
                    <section>
                        <h2>2. Description of Service</h2>
                        <p>The Bot provides AI-powered chat functionality through Discord, including:</p>
                        <ul>
                            <li>AI model integration (DeepSeek, GPT-4, Claude, etc.) via PuterClient</li>
                            <li>Message logging and audit capabilities</li>
                            <li>Direct message responses</li>
                            <li>Command-based interactions</li>
                        </ul>
                    </section>
                    
                    <section>
                        <h2>3. User Responsibilities</h2>
                        <p>Users agree not to:</p>
                        <ul>
                            <li>Use the Bot for illegal activities</li>
                            <li>Generate harmful, abusive, or offensive content</li>
                            <li>Attempt to bypass security measures</li>
                            <li>Overload the Bot with excessive requests</li>
                            <li>Share or distribute the Bot's credentials</li>
                        </ul>
                    </section>
                    
                    <section>
                        <h2>4. Data Handling</h2>
                        <p>The Bot logs messages for moderation purposes. Logs include:</p>
                        <ul>
                            <li>Message content</li>
                            <li>User information</li>
                            <li>Server and channel details</li>
                            <li>Timestamps</li>
                        </ul>
                        <p>Logs are stored locally and used solely for moderation and debugging.</p>
                    </section>
                    
                    <section>
                        <h2>5. AI Model Usage</h2>
                        <p>The Bot uses third-party AI services via PuterClient. These services have their own terms:</p>
                        <ul>
                            <li>OpenAI Terms of Service</li>
                            <li>Anthropic Claude Terms</li>
                            <li>Google Gemini Terms</li>
                            <li>DeepSeek Terms of Service</li>
                        </ul>
                    </section>
                    
                    <section>
                        <h2>6. Limitation of Liability</h2>
                        <p>The Bot is provided "as is" without warranties. We are not responsible for:</p>
                        <ul>
                            <li>AI-generated content accuracy</li>
                            <li>Service interruptions</li>
                            <li>Third-party API limitations</li>
                            <li>User misuse of the Bot</li>
                        </ul>
                    </section>
                    
                    <section>
                        <h2>7. Contact Information</h2>
                        <p>For questions about these terms, contact: support@example.com</p>
                        <p><strong>Effective Date:</strong> ${currentDate}</p>
                    </section>
                </article>
            </section>
        `;
    }
    
    // Privacy Policy page rendering
    function renderPrivacy() {
        const currentDate = new Date().toISOString().split('T')[0];
        
        return `
            <section class="page-content">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: var(--space-xl);">
                    <h1>Privacy Policy</h1>
                    <button class="btn btn-secondary" onclick="window.print()">Print / Save as PDF</button>
                </div>
                
                <article>
                    <section>
                        <h2>1. Data Collection</h2>
                        <p>The Bot collects minimal data necessary for operation:</p>
                        <ul>
                            <li><strong>Message Content:</strong> For AI processing and logging</li>
                            <li><strong>User Information:</strong> User ID, username, discriminator</li>
                            <li><strong>Server Information:</strong> Server ID, server name</li>
                            <li><strong>Channel Information:</strong> Channel ID, channel name</li>
                            <li><strong>Timestamps:</strong> Message and interaction times</li>
                        </ul>
                    </section>
                    
                    <section>
                        <h2>2. Data Usage</h2>
                        <p>Collected data is used for:</p>
                        <ul>
                            <li>Providing AI chat functionality</li>
                            <li>Message logging for moderation</li>
                            <li>Command processing and response generation</li>
                            <li>Debugging and service improvement</li>
                        </ul>
                    </section>
                    
                    <section>
                        <h2>3. Data Storage</h2>
                        <p>Data is stored:</p>
                        <ul>
                            <li><strong>Logs:</strong> Stored locally in log files</li>
                            <li><strong>Duration:</strong> Logs are retained for 30 days</li>
                            <li><strong>Security:</strong> Local file storage with standard file permissions</li>
                        </ul>
                    </section>
                    
                    <section>
                        <h2>4. Third-Party Services</h2>
                        <p>The Bot integrates with:</p>
                        <ul>
                            <li><strong>Discord:</strong> For platform functionality</li>
                            <li><strong>PuterClient:</strong> For AI model access</li>
                            <li><strong>AI Providers:</strong> OpenAI, Anthropic, Google, etc.</li>
                        </ul>
                        <p>These services have their own privacy policies.</p>
                    </section>
                    
                    <section>
                        <h2>5. User Rights</h2>
                        <p>Users have the right to:</p>
                        <ul>
                            <li>Request log deletion</li>
                            <li>Opt-out of message logging</li>
                            <li>Request data access</li>
                            <li>File privacy concerns</li>
                        </ul>
                        <p>Contact: support@example.com for privacy requests.</p>
                    </section>
                    
                    <section>
                        <h2>6. Security Measures</h2>
                        <p>We implement:</p>
                        <ul>
                            <li>Secure credential storage</li>
                            <li>Regular security updates</li>
                            <li>Access logging</li>
                            <li>Environment variable protection</li>
                        </ul>
                    </section>
                    
                    <section>
                        <h2>7. Children's Privacy</h2>
                        <p>The Bot is not intended for users under 13. We do not knowingly collect data from children.</p>
                    </section>
                    
                    <section>
                        <h2>8. Policy Updates</h2>
                        <p>This policy may be updated. Continued Bot use constitutes acceptance of changes.</p>
                        <p><strong>Effective Date:</strong> ${currentDate}</p>
                    </section>
                </article>
            </section>
        `;
    }
    
    // Event listeners for dynamic content
    function attachHomeListeners() {
        // No specific listeners needed for home page
    }
    
    function attachInteractionsListeners() {
        const saveBtn = document.getElementById('save-interactions');
        const endpointInput = document.getElementById('endpoint-url');
        
        if (saveBtn && endpointInput) {
            saveBtn.addEventListener('click', function() {
                state.interactionsEndpoint = endpointInput.value;
                localStorage.setItem('interactionsEndpoint', state.interactionsEndpoint);
                showNotification('Configuration saved successfully', 'success');
            });
        }
    }
    
    // Copy button functionality
    function initCopyButtons() {
        document.querySelectorAll('.copy-btn').forEach(button => {
            button.addEventListener('click', function() {
                const targetId = this.getAttribute('data-target');
                const targetElement = document.getElementById(targetId);
                
                if (targetElement) {
                    const textToCopy = targetElement.textContent;
                    
                    if (navigator.clipboard && window.isSecureContext) {
                        navigator.clipboard.writeText(textToCopy).then(() => {
                            showCopyFeedback(this);
                        }).catch(err => {
                            console.error('Clipboard error:', err);
                            fallbackCopy(this, textToCopy);
                        });
                    } else {
                        fallbackCopy(this, textToCopy);
                    }
                }
            });
        });
    }
    
    function showCopyFeedback(button) {
        const originalText = button.textContent;
        button.textContent = 'Copied!';
        button.style.background = 'var(--secondary)';
        button.style.color = 'white';
        
        setTimeout(() => {
            button.textContent = originalText;
            button.style.background = '';
            button.style.color = '';
        }, 2000);
    }
    
    function fallbackCopy(button, text) {
        const textArea = document.createElement('textarea');
        textArea.value = text;
        document.body.appendChild(textArea);
        textArea.select();
        
        try {
            document.execCommand('copy');
            showCopyFeedback(button);
        } catch (err) {
            console.error('Fallback copy failed:', err);
            button.textContent = 'Failed';
            setTimeout(() => {
                button.textContent = 'Copy';
            }, 2000);
        }
        
        document.body.removeChild(textArea);
    }
    
    // Notification system
    function showNotification(message, type = 'success') {
        // Remove existing notification
        const existingNotification = document.querySelector('.notification');
        if (existingNotification) {
            existingNotification.remove();
        }
        
        // Create new notification
        const notification = document.createElement('div');
        notification.className = `notification notification-${type}`;
        notification.innerHTML = `
            <div class="notification-content">
                ${type === 'success' ? '✅' : '⚠️'} ${message}
            </div>
        `;
        
        // Add styles
        notification.style.cssText = `
            position: fixed;
            top: 100px;
            right: 20px;
            background: ${type === 'error' ? 'var(--error)' : 'var(--secondary)'};
            color: white;
            padding: var(--space-md) var(--space-lg);
            border-radius: var(--radius-lg);
            box-shadow: var(--shadow-lg);
            z-index: 1000;
            transform: translateX(120%);
            transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
            font-weight: 500;
        `;
        
        document.body.appendChild(notification);
        
        // Animate in
        requestAnimationFrame(() => {
            notification.style.transform = 'translateX(0)';
        });
        
        // Remove after 3 seconds
        setTimeout(() => {
            notification.style.transform = 'translateX(120%)';
            setTimeout(() => {
                if (notification.parentNode) {
                    notification.parentNode.removeChild(notification);
                }
            }, 300);
        }, 3000);
    }
    
    // Initialize the app when DOM is loaded
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
    
    // Handle navigation clicks
    document.addEventListener('click', function(e) {
        if (e.target.matches('.nav-link')) {
            e.preventDefault();
            const route = e.target.getAttribute('data-route');
            window.location.hash = route;
            
            // Close mobile menu if open
            if (navToggle.getAttribute('aria-expanded') === 'true') {
                toggleMobileMenu();
            }
        }
    });
})();