// GENERATED BY PROMPT — Placeholder tokens used — DO NOT PASTE REAL SECRETS

(function() {
    'use strict';
    
    // State management
    const state = {
        currentRoute: '/',
        theme: localStorage.getItem('theme') || 'light',
        interactionsEndpoint: localStorage.getItem('interactionsEndpoint') || 'https://example.local/api/interactions',
        verificationUrl: localStorage.getItem('verificationUrl') || 'https://example.local/verify-user'
    };
    
    // DOM Elements
    const routerView = document.getElementById('router-view');
    const navToggle = document.querySelector('.nav-toggle');
    const navMenu = document.getElementById('nav-menu');
    const connectBtn = document.getElementById('connect-btn');
    const connectModal = document.getElementById('connect-modal');
    const modalClose = document.querySelector('.modal-close');
    const themeToggle = document.getElementById('theme-toggle');
    
    // Initialize the application
    function init() {
        setupEventListeners();
        setupRouting();
        applyTheme(state.theme);
        renderRoute(state.currentRoute);
    }
    
    // Event Listeners
    function setupEventListeners() {
        // Navigation toggle for mobile
        navToggle.addEventListener('click', toggleMobileMenu);
        
        // Modal controls
        connectBtn.addEventListener('click', openConnectModal);
        modalClose.addEventListener('click', closeConnectModal);
        connectModal.addEventListener('click', function(e) {
            if (e.target === connectModal) closeConnectModal();
        });
        
        // Theme toggle
        themeToggle.addEventListener('click', toggleTheme);
        
        // Handle escape key for modals
        document.addEventListener('keydown', function(e) {
            if (e.key === 'Escape') {
                closeConnectModal();
            }
        });
        
        // Handle hash changes for routing
        window.addEventListener('hashchange', handleHashChange);
    }
    
    // Mobile menu functionality
    function toggleMobileMenu() {
        const isExpanded = navToggle.getAttribute('aria-expanded') === 'true';
        navToggle.setAttribute('aria-expanded', !isExpanded);
        navMenu.setAttribute('aria-expanded', !isExpanded);
    }
    
    // Modal functionality
    function openConnectModal() {
        connectModal.setAttribute('aria-hidden', 'false');
        document.body.style.overflow = 'hidden';
    }
    
    function closeConnectModal() {
        connectModal.setAttribute('aria-hidden', 'true');
        document.body.style.overflow = '';
    }
    
    // Theme functionality
    function toggleTheme() {
        const newTheme = state.theme === 'light' ? 'dark' : 'light';
        applyTheme(newTheme);
        state.theme = newTheme;
        localStorage.setItem('theme', newTheme);
    }
    
    function applyTheme(theme) {
        document.documentElement.setAttribute('data-theme', theme);
        const themeIcon = themeToggle.querySelector('.theme-icon');
        themeIcon.textContent = theme === 'light' ? '🌙' : '☀️';
    }
    
    // Routing functionality
    function setupRouting() {
        // Set initial route from hash or default to home
        const hash = window.location.hash.slice(1) || '/';
        state.currentRoute = hash;
        updateActiveNavLink(hash);
    }
    
    function handleHashChange() {
        const hash = window.location.hash.slice(1) || '/';
        state.currentRoute = hash;
        updateActiveNavLink(hash);
        renderRoute(hash);
    }
    
    function updateActiveNavLink(route) {
        document.querySelectorAll('.nav-link').forEach(link => {
            link.classList.remove('active');
            if (link.getAttribute('data-route') === route) {
                link.classList.add('active');
            }
        });
    }
    
    // Route rendering
    function renderRoute(route) {
        let content = '';
        
        switch(route) {
            case '/':
                content = renderHome();
                break;
            case '/interactions':
                content = renderInteractions();
                break;
            case '/linked-roles':
                content = renderLinkedRoles();
                break;
            case '/tos':
                content = renderTOS();
                break;
            case '/privacy':
                content = renderPrivacy();
                break;
            default:
                content = renderHome();
        }
        
        routerView.innerHTML = content;
        
        // Attach event listeners for dynamic content
        if (route === '/interactions') {
            attachInteractionsListeners();
        } else if (route === '/linked-roles') {
            attachLinkedRolesListeners();
        } else if (route === '/') {
            attachHomeListeners();
        }
        
        // Re-initialize copy buttons for code blocks
        initCopyButtons();
    }
    
    // Home page rendering
    function renderHome() {
        return `
            <section class="hero">
                <h1 class="hero-title">Discord App — Developer Console & Links</h1>
                <p class="hero-subtitle">Configure and manage your Discord application endpoints, linked roles verification, and legal documentation in one place.</p>
                
                <div class="features">
                    <div class="feature-card">
                        <div class="feature-icon">🔒</div>
                        <h3 class="feature-title">Secure Endpoints</h3>
                        <p class="feature-description">Configure and test your interactions endpoint with proper security validation and signature verification.</p>
                    </div>
                    <div class="feature-card">
                        <div class="feature-icon">🔗</div>
                        <h3 class="feature-title">Role Linking</h3>
                        <p class="feature-description">Set up linked roles verification to enable role assignment based on external criteria and user verification.</p>
                    </div>
                    <div class="feature-card">
                        <div class="feature-icon">⚖️</div>
                        <h3 class="feature-title">Legal & Privacy</h3>
                        <p class="feature-description">Manage your Terms of Service and Privacy Policy with professional templates and easy customization.</p>
                    </div>
                </div>
                
                <div class="preview-panel">
                    <h3 class="preview-title">Interactions Endpoint Preview</h3>
                    <div class="url-input-group">
                        <input type="text" class="url-input" id="preview-url" 
                               value="${state.interactionsEndpoint}" 
                               placeholder="https://example.local/api/interactions">
                        <button class="btn btn-primary" id="update-preview">Update Preview</button>
                    </div>
                    <div class="code-block">
                        <button class="copy-btn" data-target="preview-curl">Copy</button>
                        <pre id="preview-curl">curl -X POST \\\n  "${state.interactionsEndpoint}" \\\n  --header "Content-Type: application/json" \\\n  --header "Authorization: Bearer &lt;YOUR_BOT_TOKEN&gt;" \\\n  --data '{\n    "type": 1,\n    "token": "{{INTERACTION_TOKEN}}",\n    "member": {\n      "user": {\n        "id": "{{USER_ID}}"\n      }\n    }\n  }'</pre>
                    </div>
                    <div class="warning-box">
                        <strong>Security Warning:</strong> This is a preview only. Do not paste real tokens or secrets. All interactions should be validated server-side.
                    </div>
                </div>
            </section>
        `;
    }
    
    // Interactions page rendering
    function renderInteractions() {
        return `
            <section class="page-content">
                <h1>Interactions Endpoint</h1>
                <p>Configure your Discord application to receive interactions via HTTP POSTs instead of through the Gateway.</p>
                
                <div class="warning-box">
                    <strong>Important:</strong> Never paste real tokens or secrets into this form. This is for preview and testing purposes only.
                </div>
                
                <form id="interactions-form">
                    <div class="form-group">
                        <label for="endpoint-url" class="form-label">Interactions Endpoint URL</label>
                        <input type="url" id="endpoint-url" class="form-input" 
                               value="${state.interactionsEndpoint}" 
                               placeholder="https://example.local/api/interactions">
                    </div>
                    
                    <div class="form-group">
                        <label for="method-select" class="form-label">HTTP Method</label>
                        <select id="method-select" class="form-select">
                            <option value="POST" selected>POST</option>
                            <option value="GET">GET</option>
                        </select>
                    </div>
                    
                    <div class="form-checkbox">
                        <input type="checkbox" id="placeholder-only" checked>
                        <label for="placeholder-only">Use placeholder only — do not call external servers</label>
                    </div>
                    
                    <button type="button" class="btn btn-primary" id="save-interactions">Save Preview</button>
                </form>
                
                <div id="curl-preview" class="code-block" style="margin-top: 2rem; display: none;">
                    <button class="copy-btn" data-target="generated-curl">Copy</button>
                    <pre id="generated-curl"></pre>
                </div>
                
                <h2 style="margin-top: 3rem;">Sample Request & Response</h2>
                <p>Below is an example of what your server might receive and should respond with:</p>
                
                <div class="code-block">
                    <button class="copy-btn" data-target="sample-request">Copy</button>
                    <pre id="sample-request">// Sample Interaction Request\n{\n  "type": 2,\n  "token": "{{INTERACTION_TOKEN}}",\n  "member": {\n    "user": {\n      "id": "{{USER_ID}}",\n      "username": "{{USERNAME}}",\n      "avatar": "{{AVATAR}}",\n      "discriminator": "{{DISCRIMINATOR}}"\n    },\n    "roles": ["{{ROLE_ID}}"],\n    "permissions": "{{PERMISSIONS}}"\n  },\n  "id": "{{INTERACTION_ID}}",\n  "guild_id": "{{GUILD_ID}}",\n  "channel_id": "{{CHANNEL_ID}}",\n  "data": {\n    "name": "command_name",\n    "id": "{{COMMAND_ID}}",\n    "options": []\n  }\n}</pre>
                </div>
                
                <div class="code-block">
                    <button class="copy-btn" data-target="sample-response">Copy</button>
                    <pre id="sample-response">// Sample Interaction Response\n{\n  "type": 4,\n  "data": {\n    "content": "Hello, world!",\n    "embeds": [],\n    "components": []\n  }\n}</pre>
                </div>
                
                <div class="warning-box">
                    <h3>Security Recommendations</h3>
                    <ul>
                        <li>Always verify interaction signatures using the <code>X-Signature-Ed25519</code> and <code>X-Signature-Timestamp</code> headers</li>
                        <li>Validate that timestamps are recent to prevent replay attacks</li>
                        <li>Never trust user input without validation</li>
                        <li>Store your public key securely and use it to verify requests</li>
                        <li>Respond to PING interactions with PONG (type 1) immediately</li>
                    </ul>
                </div>
            </section>
        `;
    }
    
    // Linked Roles page rendering
    function renderLinkedRoles() {
        return `
            <section class="page-content">
                <h1>Linked Roles Verification</h1>
                <p>Configure role verification URLs to enable your application as a requirement in server role settings.</p>
                
                <form id="linked-roles-form">
                    <div class="form-group">
                        <label for="verification-url" class="form-label">Verification URL</label>
                        <input type="url" id="verification-url" class="form-input" 
                               value="${state.verificationUrl}" 
                               placeholder="https://example.local/verify-user">
                    </div>
                    
                    <button type="button" class="btn btn-primary" id="save-verification">Save Preview</button>
                </form>
                
                <h2>How Linked Roles Work</h2>
                <p>Linked Roles allow server administrators to require users to link their accounts with your application to gain specific roles.</p>
                
                <div style="background: var(--bg-secondary); padding: var(--space-lg); border-radius: var(--radius-lg); margin: var(--space-lg) 0;">
                    <h3 style="margin-top: 0;">User Flow:</h3>
                    <ol>
                        <li>User attempts to join a server or access role-restricted content</li>
                        <li>Discord redirects the user to your verification URL with OAuth2 parameters</li>
                        <li>Your application authenticates the user and checks eligibility</li>
                        <li>If eligible, redirect back to Discord with an access token</li>
                        <li>Discord grants the user the appropriate role</li>
                    </ol>
                </div>
                
                <h2>Example Verification Payload</h2>
                <p>When Discord redirects to your verification URL, you'll receive query parameters like:</p>
                
                <div class="code-block">
                    <button class="copy-btn" data-target="verification-payload">Copy</button>
                    <pre id="verification-payload">// OAuth2 Query Parameters\n{\n  "client_id": "{{CLIENT_ID}}",\n  "redirect_uri": "https://discord.com/oauth2/authorize",\n  "response_type": "code",\n  "scope": "role_connections.write identify",\n  "state": "{{RANDOM_STATE}}",\n  "prompt": "consent",\n  "code_challenge": "{{CODE_CHALLENGE}}",\n  "code_challenge_method": "S256"\n}</pre>
                </div>
                
                <h2>Verification Flow Diagram</h2>
                <div style="display: flex; flex-direction: column; gap: var(--space-md); margin: var(--space-lg) 0;">
                    <div style="background: var(--bg-secondary); padding: var(--space-md); border-radius: var(--radius-md); text-align: center;">
                        User clicks role requirement
                    </div>
                    <div style="text-align: center;">↓</div>
                    <div style="background: var(--bg-secondary); padding: var(--space-md); border-radius: var(--radius-md); text-align: center;">
                        Discord redirects to your verification URL
                    </div>
                    <div style="text-align: center;">↓</div>
                    <div style="background: var(--bg-secondary); padding: var(--space-md); border-radius: var(--radius-md); text-align: center;">
                        Your server validates user and criteria
                    </div>
                    <div style="text-align: center;">↓</div>
                    <div style="background: var(--bg-secondary); padding: var(--space-md); border-radius: var(--radius-md); text-align: center;">
                        Redirect back to Discord with metadata
                    </div>
                    <div style="text-align: center;">↓</div>
                    <div style="background: var(--bg-secondary); padding: var(--space-md); border-radius: var(--radius-md); text-align: center;">
                        Role is assigned to user
                    </div>
                </div>
                
                <div class="warning-box">
                    <h3>Security Considerations</h3>
                    <ul>
                        <li>Implement proper OAuth2 flow with state parameter validation</li>
                        <li>Only request the minimum scopes needed for verification</li>
                        <li>Store user data securely and respect privacy</li>
                        <li>Implement rate limiting to prevent abuse</li>
                        <li>Use HTTPS for all verification endpoints</li>
                    </ul>
                </div>
            </section>
        `;
    }
    
    // Terms of Service page rendering
    function renderTOS() {
        return `
            <section class="page-content">
                <div style="display: flex; justify-content: between; align-items: center; margin-bottom: var(--space-xl);">
                    <h1>Terms of Service</h1>
                    <button class="btn btn-secondary" onclick="window.print()">Print / Save as PDF</button>
                </div>
                
                <article>
                    <section>
                        <h2>1. Introduction</h2>
                        <p>Welcome to {{ORGANIZATION_NAME}} ("we," "our," or "us"). These Terms of Service ("Terms") govern your use of our Discord application and related services (collectively, the "Service").</p>
                        <p>By using our Service, you agree to be bound by these Terms. If you disagree with any part of the Terms, you may not access the Service.</p>
                    </section>
                    
                    <section>
                        <h2>2. Acceptance of Terms</h2>
                        <p>By accessing or using our Service, you confirm that you can form a binding contract with us, that you accept these Terms, and that you agree to comply with them. Your access to and use of the Service is also subject to our Privacy Policy.</p>
                    </section>
                    
                    <section>
                        <h2>3. Description of Service</h2>
                        <p>Our Service provides Discord integration features including but not limited to:</p>
                        <ul>
                            <li>Custom Discord application commands and interactions</li>
                            <li>Linked roles verification and assignment</li>
                            <li>Server management tools</li>
                            <li>User authentication and authorization services</li>
                        </ul>
                        <p>We reserve the right to modify, suspend, or discontinue the Service (or any part of it) at any time with or without notice.</p>
                    </section>
                    
                    <section>
                        <h2>4. User Obligations and Prohibited Conduct</h2>
                        <p>You agree not to use the Service to:</p>
                        <ul>
                            <li>Violate any applicable laws, regulations, or third-party rights</li>
                            <li>Distribute malware, viruses, or other harmful code</li>
                            <li>Spam, harass, or abuse other users</li>
                            <li>Impersonate any person or entity</li>
                            <li>Attempt to gain unauthorized access to any part of the Service</li>
                            <li>Reverse engineer, decompile, or disassemble any portion of the Service</li>
                            <li>Use the Service for any illegal or unauthorized purpose</li>
                        </ul>
                    </section>
                    
                    <section>
                        <h2>5. Third-Party Services and Integrations</h2>
                        <p>Our Service integrates with Discord Inc.'s platform. Your use of Discord is subject to Discord's own Terms of Service and Privacy Policy. We are not responsible for Discord's services or any issues arising from your use of Discord.</p>
                        <p>When you use our Service through Discord, we may receive certain information from Discord as described in our Privacy Policy.</p>
                    </section>
                    
                    <section>
                        <h2>6. Liability Limitations and Disclaimers</h2>
                        <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED.</p>
                        <p>IN NO EVENT SHALL WE BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE SERVICE.</p>
                    </section>
                    
                    <section>
                        <h2>7. Changes to Terms</h2>
                        <p>We reserve the right to modify these Terms at any time. If we make changes, we will provide notice through the Service or by other means. Your continued use of the Service after any modification constitutes your acceptance of the new Terms.</p>
                    </section>
                    
                    <section>
                        <h2>8. Contact Information</h2>
                        <p>If you have any questions about these Terms, please contact us at {{SUPPORT_EMAIL}}.</p>
                        <p><strong>Effective Date:</strong> ${new Date().toISOString().split('T')[0]}</p>
                    </section>
                </article>
            </section>
        `;
    }
    
    // Privacy Policy page rendering
    function renderPrivacy() {
        return `
            <section class="page-content">
                <div style="display: flex; justify-content: between; align-items: center; margin-bottom: var(--space-xl);">
                    <h1>Privacy Policy</h1>
                    <button class="btn btn-secondary" onclick="window.print()">Print / Save as PDF</button>
                </div>
                
                <article>
                    <section>
                        <h2>1. Introduction</h2>
                        <p>This Privacy Policy explains how {{ORGANIZATION_NAME}} ("we," "our," or "us") collects, uses, and protects your information when you use our Discord application and related services (the "Service").</p>
                        <p>We are committed to protecting your privacy and handling your data transparently and securely.</p>
                    </section>
                    
                    <section>
                        <h2>2. Information We Collect</h2>
                        <p>We collect minimal information necessary to provide the Service:</p>
                        <ul>
                            <li><strong>Discord User Information:</strong> When you interact with our Service through Discord, we may receive your Discord user ID, username, discriminator, avatar, and server information.</li>
                            <li><strong>Interaction Data:</strong> We may log command usage, timestamps, and server IDs to maintain and improve the Service.</li>
                            <li><strong>Technical Information:</strong> We may collect IP addresses, browser type, and other technical data for security and analytics purposes.</li>
                        </ul>
                    </section>
                    
                    <section>
                        <h2>3. How We Use Your Information</h2>
                        <p>We use the information we collect to:</p>
                        <ul>
                            <li>Provide, maintain, and improve the Service</li>
                            <li>Process your commands and interactions</li>
                            <li>Verify user identities for linked roles</li>
                            <li>Ensure the security and integrity of the Service</li>
                            <li>Comply with legal obligations</li>
                        </ul>
                        <p>We do not sell your personal information to third parties.</p>
                    </section>
                    
                    <section>
                        <h2>4. Data Retention</h2>
                        <p>We retain your information only for as long as necessary to fulfill the purposes outlined in this Privacy Policy. Typically, we retain:</p>
                        <ul>
                            <li>User data: While your account is active and for 30 days after deactivation</li>
                            <li>Interaction logs: For up to 90 days for debugging and analytics</li>
                            <li>Server configuration data: Until the server removes our application</li>
                        </ul>
                    </section>
                    
                    <section>
                        <h2>5. Data Sharing and Third Parties</h2>
                        <p>We may share your information in the following circumstances:</p>
                        <ul>
                            <li><strong>With Discord:</strong> As necessary to provide the Service through their platform</li>
                            <li><strong>Service Providers:</strong> With trusted third parties who assist us in operating our Service</li>
                            <li><strong>Legal Requirements:</strong> When required by law or to protect our rights</li>
                        </ul>
                        <p>We use appropriate contractual and technical safeguards with third parties who process data on our behalf.</p>
                    </section>
                    
                    <section>
                        <h2>6. Your Rights</h2>
                        <p>Depending on your jurisdiction, you may have the following rights regarding your personal information:</p>
                        <ul>
                            <li><strong>Access:</strong> You can request a copy of the personal information we hold about you</li>
                            <li><strong>Correction:</strong> You can request correction of inaccurate information</li>
                            <li><strong>Deletion:</strong> You can request deletion of your personal information</li>
                            <li><strong>Portability:</strong> You can request your data in a structured, machine-readable format</li>
                            <li><strong>Objection:</strong> You can object to certain processing of your information</li>
                        </ul>
                        <p>To exercise these rights, please contact us at {{SUPPORT_EMAIL}}.</p>
                    </section>
                    
                    <section>
                        <h2>7. Security</h2>
                        <p>We implement appropriate technical and organizational measures to protect your information against unauthorized access, alteration, disclosure, or destruction. However, no internet transmission is completely secure, and we cannot guarantee absolute security.</p>
                    </section>
                    
                    <section>
                        <h2>8. International Transfers</h2>
                        <p>Your information may be transferred to and processed in countries other than your own. We ensure appropriate safeguards are in place for such transfers as required by applicable law.</p>
                    </section>
                    
                    <section>
                        <h2>9. Children's Privacy</h2>
                        <p>Our Service is not directed to individuals under the age of 13 (or other age as required by local law). We do not knowingly collect personal information from children. If we become aware that we have collected personal information from a child, we will take steps to delete such information.</p>
                    </section>
                    
                    <section>
                        <h2>10. Changes to This Policy</h2>
                        <p>We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new policy on our Service and updating the effective date.</p>
                    </section>
                    
                    <section>
                        <h2>11. Contact Us</h2>
                        <p>If you have any questions about this Privacy Policy or our data practices, please contact us at {{SUPPORT_EMAIL}}.</p>
                        <p><strong>Effective Date:</strong> ${new Date().toISOString().split('T')[0]}</p>
                    </section>
                </article>
            </section>
        `;
    }
    
    // Event listeners for dynamic content
    function attachHomeListeners() {
        const updatePreviewBtn = document.getElementById('update-preview');
        const previewUrlInput = document.getElementById('preview-url');
        
        if (updatePreviewBtn && previewUrlInput) {
            updatePreviewBtn.addEventListener('click', function() {
                state.interactionsEndpoint = previewUrlInput.value;
                localStorage.setItem('interactionsEndpoint', state.interactionsEndpoint);
                
                const curlElement = document.getElementById('preview-curl');
                if (curlElement) {
                    curlElement.textContent = curlElement.textContent.replace(
                        /https?:\/\/[^\s]+/g, 
                        state.interactionsEndpoint
                    );
                }
                
                // Show confirmation
                showNotification('Preview updated successfully');
            });
        }
    }
    
    function attachInteractionsListeners() {
        const saveBtn = document.getElementById('save-interactions');
        const endpointInput = document.getElementById('endpoint-url');
        const methodSelect = document.getElementById('method-select');
        const placeholderCheckbox = document.getElementById('placeholder-only');
        
        if (saveBtn && endpointInput) {
            saveBtn.addEventListener('click', function() {
                state.interactionsEndpoint = endpointInput.value;
                localStorage.setItem('interactionsEndpoint', state.interactionsEndpoint);
                
                // Generate curl command preview
                const method = methodSelect.value;
                const usePlaceholder = placeholderCheckbox.checked;
                
                const curlPreview = document.getElementById('curl-preview');
                const generatedCurl = document.getElementById('generated-curl');
                
                if (curlPreview && generatedCurl) {
                    let curlCommand = `curl -X ${method} \\\\\n  "${state.interactionsEndpoint}" \\\\\n  --header "Content-Type: application/json" \\\\\n  --header "Authorization: Bearer <YOUR_BOT_TOKEN>"`;
                    
                    if (method === 'POST') {
                        curlCommand += ` \\\\\n  --data '{\n    "type": 1,\n    "token": "{{INTERACTION_TOKEN}}",\n    "member": {\n      "user": {\n        "id": "{{USER_ID}}"\n      }\n    }\n  }'`;
                    }
                    
                    generatedCurl.textContent = curlCommand;
                    curlPreview.style.display = 'block';
                }
                
                showNotification('Interactions endpoint saved to preview');
            });
        }
    }
    
    function attachLinkedRolesListeners() {
        const saveBtn = document.getElementById('save-verification');
        const verificationInput = document.getElementById('verification-url');
        
        if (saveBtn && verificationInput) {
            saveBtn.addEventListener('click', function() {
                state.verificationUrl = verificationInput.value;
                localStorage.setItem('verificationUrl', state.verificationUrl);
                showNotification('Verification URL saved to preview');
            });
        }
    }
    
    // Copy button functionality
    function initCopyButtons() {
        document.querySelectorAll('.copy-btn').forEach(button => {
            button.addEventListener('click', function() {
                const targetId = this.getAttribute('data-target');
                const targetElement = document.getElementById(targetId);
                
                if (targetElement) {
                    const textToCopy = targetElement.textContent;
                    
                    navigator.clipboard.writeText(textToCopy).then(() => {
                        const originalText = this.textContent;
                        this.textContent = 'Copied!';
                        
                        setTimeout(() => {
                            this.textContent = originalText;
                        }, 2000);
                    }).catch(err => {
                        console.error('Failed to copy text: ', err);
                        // Fallback for browsers that don't support clipboard API
                        const textArea = document.createElement('textarea');
                        textArea.value = textToCopy;
                        document.body.appendChild(textArea);
                        textArea.select();
                        document.execCommand('copy');
                        document.body.removeChild(textArea);
                        
                        const originalText = this.textContent;
                        this.textContent = 'Copied!';
                        
                        setTimeout(() => {
                            this.textContent = originalText;
                        }, 2000);
                    });
                }
            });
        });
    }
    
    // Notification system
    function showNotification(message, type = 'success') {
        // Remove existing notification
        const existingNotification = document.querySelector('.notification');
        if (existingNotification) {
            existingNotification.remove();
        }
        
        // Create new notification
        const notification = document.createElement('div');
        notification.className = `notification notification-${type}`;
        notification.textContent = message;
        notification.style.cssText = `
            position: fixed;
            top: 100px;
            right: 20px;
            background: ${type === 'error' ? 'var(--error)' : 'var(--success)'};
            color: white;
            padding: var(--space-md) var(--space-lg);
            border-radius: var(--radius-md);
            box-shadow: var(--shadow-lg);
            z-index: 1000;
            transition: transform 0.3s ease;
        `;
        
        document.body.appendChild(notification);
        
        // Animate in
        setTimeout(() => {
            notification.style.transform = 'translateX(0)';
        }, 10);
        
        // Remove after 3 seconds
        setTimeout(() => {
            notification.style.transform = 'translateX(100%)';
            setTimeout(() => {
                if (notification.parentNode) {
                    notification.parentNode.removeChild(notification);
                }
            }, 300);
        }, 3000);
    }
    
    // Initialize the app when DOM is loaded
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();